### PR TITLE
Refactoring of PasswordSecureGeneratorService

### PR DESCRIPTION
**Pull request by jiridrimal**
Deleting unnecessary initialization method and generateSequenceOfCharacters method in PasswordSecureGeneratorService.
And other refactoring stuff - only refactoring...I hope

UPDATE:
Last approved PR  #42 is better but it still has wrong character list (there is one non-printable character). I assuimg that my implementation is better because my character list is as it should be (according to the documentation). 

Please accept this PR already (it's been 10 days) I must resolve one more PR.
Thank you!
Jiří Dřímal (st64297)

### CODE REVIEW

**Comment by rodi0878** [comment]
Youre filling static attribute from instance constructor - this may lead to mess. Please fix this issue before merging may proceed.

**Comment by jiridrimal** [comment]
I updated PR. I hope everything is ok now.

**Comment by jiridrimal** [comment]
Travis this is not my fault...I think :)

**Comment by rodi0878** [comment]
I rereviewed this PR and now i'm seeing that you are changing the collection with characters. Original version has different set of characters. What reason is behind this change? I'm missing it in description

**Comment by jiridrimal** [comment]
I don't know what you mean. Original version has same set of characters (printable characters). Can you please tell me exactly where you see the problem?

**Comment by rodi0878** [comment]
No, please execute original code and your code and compare created sets of characters. They arent same

**Comment by jiridrimal** [comment]
Ok you mean these **2 characters** that are not missing (compared to the original)? 
Well I was thinking that this is a rigth way to use this characterList - you wrote me that any restriction of generated alphabet is bad. 
I don't understate why there is 2 characters missing. But if you want the character list to be like that I can preserve this weird character generation.
Please let me know what do you want me to do.

**Comment by rodi0878** [comment]
I already said that: "What reason is behind this change? I'm missing it in description"

**Comment by jiridrimal** [comment]
So because you just merge PR that is dealing with this issue - so I assume there is no change anymore. But that merge you approved also add new non-printable character. With my implementation there are no issues like that and it's been this way for 10 days. So only "issue" is my description?

**Pull request merged**
