### PR TITLE
Refactor Category

### PR DESCRIPTION
**Pull request by st55425**
Added public class modifier
Changed children attribute from List to Set - to avoid duplicate child in structure
Overrode and tested equals and hashCode methods (needed for properly work of children set)
Implemented null object pattern for parents

### CODE REVIEW

**Comment by rodi0878** [comment]
You have few good ideas but there are severe issues:

- set and hashset are not preserving order of elements; this is requirement for stable order of elements defined by user choices
- singleton in nullcat is implemented poorly - wrong lazy initialization, unnecessary creation of objects instead of caching them

Please resolve mentioned before merging

**Comment by st55425** [comment]
Resolved issues:
NullCategory singleton implemented as Bill Pugh Singleton Implementation, attributes children and name is now cached.
Attribute children was changed to SortedSet and its implementation (TreeSet) to preserve ordering. For this purpose was implemented and tested interface Comparable and its method compareTo.

**Comment by rodi0878** [comment]
- SortedSet is still not really what users want, you're forcing them to use your sort order, not what they wants
- calling clear in null category is not really good, better is to use Collections.unmodifiable... to ensure, that this is not mutable collection

**Comment by st55425** [comment]
Resolved issues:
SortedSet changed back to List.
In NullCadegory was used Collections.unmodifiableList.

**Pull request merged**
