### PR TITLE
Custom serializer and Deserializer using JackSon, Test for passwords with parameters

### PR DESCRIPTION
**Pull request by issayjov97**
Added features:
- Custom serializer Deserializer using JackSon
-  Test for passwords with parameters

### CODE REVIEW

**Comment by rodi0878** [comment]
As I said before: project will target only LTS versions of java - Java 8 or Java 11. This patch contains mixed use of Java 11 and Java 9 and thus is unmergeable. Please fix this.

Patch also contains file "test.txt" which shouldnt be here.

**Comment by issayjov97** [comment]
Sorry Mr. Divis, i did not know that my Java compiler was using target bytecode version Java 9. Now it should be ok. Thanks

**Comment by rodi0878** [comment]
There are still multiple configurations that target Java 9 and not 11. Please fix, otherwise this will be closed without merging.

**Comment by rodi0878** [comment]
" <source>9</source>"...

**Pull request closed without merging**
