### PR TITLE
PR2 - Refactor method for finding entry by title 

### PR DESCRIPTION
**Pull request by xPeep**
Convert foreach to stream and filter by condition.

### CODE REVIEW

**Comment by rodi0878** [comment]
Looks good but please provide unit test for this method so we can be sure that it works correctly

**Comment by xPeep** [comment]
Unit test for refactored method added.

**Comment by rodi0878** [comment]
Referencing file (new File("/tmp/test")) is not good in unit test

**Comment by xPeep** [comment]
This file was redundant and was deleted because of  lack usage in unit test.

**Pull request merged**
